spring:
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      hikari:
        jdbc-url: jdbc:h2:~/test;AUTO_SERVER=true
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true
        output:
          ansi:
            enabled: always
      database: h2
  logging:
    level:
      org.hibernate.type.descriptor.sql.BasicExtractor: ERROR
      org.springframework.web.client: ERROR
      org.springframework.web.HttpLogging: ERROR
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
      com.tagntagger.core.web.filter.ExceptionFilter: ERROR